ALTER TABLE `doctors`
ADD COLUMN `first_name` VARCHAR(100) DEFAULT NULL AFTER `user_id`,
ADD COLUMN `last_name` VARCHAR(100) DEFAULT NULL AFTER `first_name`,
ADD COLUMN `email` VARCHAR(255) DEFAULT NULL AFTER `phone`,
ADD COLUMN `address` VARCHAR(255) DEFAULT NULL AFTER `email`;

ALTER TABLE `secretaries`
ADD COLUMN `first_name` VARCHAR(100) DEFAULT NULL AFTER `user_id`,
ADD COLUMN `last_name` VARCHAR(100) DEFAULT NULL AFTER `first_name`,
ADD COLUMN `email` VARCHAR(255) DEFAULT NULL AFTER `phone`,
ADD COLUMN `address` VARCHAR(255) DEFAULT NULL AFTER `email`;
