packages:
  - 'client'
  - 'server'
overrides:
  'form-data@>=2 <3': ^2.5.6
allowBuilds:
  '@github/keytar': true
  bcrypt: true
  esbuild: true
  node-pty: true
  sharp: true
  unrs-resolver: true
  workerd: true
