module.exports = {
  MEDICAL_REQUEST_CREATED: 'MEDICAL_REQUEST_CREATED',
  MEDICAL_REQUEST_UPDATED: 'MEDICAL_REQUEST_UPDATED',
  MEDICAL_REQUEST_DELETED: 'MEDICAL_REQUEST_DELETED',
  APPOINTMENT_COMPLETED: 'APPOINTMENT_COMPLETED'
};
