export const ICONS = {
    // Navigation / Sidebar
    DASHBOARD: 'dashboard',
    APPOINTMENTS: 'calendar_month',
    PATIENTS: 'groups',
    INSURANCES: 'monitor_heart',
    RENTALS: 'domain',
    REQUESTS: 'assignment',
    DOCUMENTS: 'folder_open',
    DOCTORS: 'medical_services',
    FINANCES: 'payments',
    REPORTS: 'assessment',
    LOGS: 'history_edu',
    USERS: 'manage_accounts',
    INSTITUTIONS: 'account_balance',
    CONFIG: 'settings',
    PROFILE: 'person',
    SPREADSHEETS: 'table_chart',
    LANGUAGE: 'language',
    LOGOUT: 'logout',

    // Stats / Dashboard
    STATS: 'analytics',
    TODAY: 'calendar_today',
    WEEK: 'view_week',
    MONTH: 'date_range',
    GROWTH: 'trending_up',
    NEW: 'auto_awesome',
    FLARE: 'flare',
    CALENDAR_TODAY: 'calendar_today',
    BAR_CHART: 'bar_chart',

    // Actions
    ADD: 'add',
    ADD_CIRCLE: 'add_circle',
    EDIT: 'edit',
    EDIT_NOTE: 'edit_note',
    DELETE: 'delete',
    DELETE_FOREVER: 'delete_forever',
    DELETE_SWEEP: 'delete_sweep',
    SAVE: 'save',
    SEARCH: 'search',
    SEND: 'send',
    SYNC: 'sync',
    PRINT: 'print',
    CLOSE: 'close',
    CANCEL: 'cancel',
    COPY: 'content_copy',
    CHECK: 'check',
    DONE_ALL: 'done_all',
    REJECT: 'block',
    RESTORE: 'restore',
    VIEW_LIST: 'view_list',
    VIEW: 'visibility',

    // Status / Medical
    PENDING: 'timer',
    COMPLETED: 'task_alt',
    ARRIVED: 'meeting_room',
    CONFIRMED: 'check_circle',
    VIRTUAL: 'videocam',
    PRESCRIPTION: 'medication',
    HISTORY: 'history',
    LICENSE: 'badge',
    CERTIFICATE: 'verified',
    WARNING: 'warning',
    INFO: 'info',
    NOTES: 'notes',
    CHAT: 'chat',
    NOTIFICATIONS: 'notifications_active',
    SMARTPHONE: 'smartphone',
    PHONE: 'call',
    MAIL: 'mail',
    MAP: 'map',
};
